import streamlit as st
st.title("hello streamlit")
st.write("hi mrecw")
st.header("byytexl")
st.subheader("bytexl234")
st.text_input("enter your name")
st.number_input("enter your age")
st.text_area("enter the address")
st.selectbox("enter the gender",["f","m","other"])
st.slider("select your age",0,100)
st.checkbox("i agree")
options=st.selectbox("select an option",["option1","option2","option3"])
st.write("you selected:",options)
st.radio("select your gender",["male","female","other"])
st.sidebar.title("Siderbar")
st.sidebar.write("this is siderbar")
st.sidebar.text_input("enter your email")
col1, col2 = st.columns(2)
with col1:
    st.write("Column 1")
    col1.text_input("enter your name in column 1")
with col2:
    st.write("Column 2")
    col2.text_input("enter your name in column 2")
st.text_input("enter your name",type="password")
st.number_input("enter your age",min_value=0,max_value=120,step=1)
st.button("submit")
st.write("[google](https://mrecwexamcell.com/)")
st.date_input("select a date")
st.time_input("select a time")
st.color_picker("pick a color")
st.file_uploader("upload file")
st.progress(50)
st.balloons()
st.snow()

st.image("bts.png",caption="bts",width=400)


